name: Publish NPM Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install NPM Packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Build TypeScript
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Publish SDK
        run: |
          echo '//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}' > .npmrc
          npm publish --access public
